/* P1.5 tectonic context: PB2002 step classes + plate polygons.
   PB2002 STEPCLASS: SUB, OSR, CRB, OTF, CTF, OCB, CCB. */
let plateStepData=empty,platePolygonData=empty;
const STEP_META={SUB:{family:'subduction',label:'Subduction zone'},OSR:{family:'divergent',label:'Oceanic spreading ridge'},CRB:{family:'divergent',label:'Continental rift boundary'},OTF:{family:'transform',label:'Oceanic transform fault'},CTF:{family:'transform',label:'Continental transform fault'},OCB:{family:'convergent',label:'Oceanic convergent boundary'},CCB:{family:'convergent',label:'Continental convergent boundary'}};
const TECTONIC_LAYERS=['tectonic-subduction','tectonic-convergent','tectonic-divergent','tectonic-transform','tectonic-other'];
const POINT_HOVER_LAYERS=['activity','volcanoes','earthquakes'];
function ensureTectonicLayers(){
  if(!map.getSource('plate-polygons'))map.addSource('plate-polygons',{type:'geojson',data:platePolygonData});
  if(!map.getLayer('plate-polygons'))map.addLayer({id:'plate-polygons',type:'fill',source:'plate-polygons',paint:{'fill-color':'#63d7e6','fill-opacity':.025}});
  if(!map.getLayer('plate-polygon-lines'))map.addLayer({id:'plate-polygon-lines',type:'line',source:'plate-polygons',minzoom:2,paint:{'line-color':'rgba(99,215,230,.10)','line-width':.6}});
  if(!map.getSource('plate-steps'))map.addSource('plate-steps',{type:'geojson',data:plateStepData});
  const specs=[['tectonic-subduction',['==',['get','Boundary_Family'],'subduction'],'#ff8b62',3.2],['tectonic-convergent',['==',['get','Boundary_Family'],'convergent'],'#ffbd66',2.5],['tectonic-divergent',['==',['get','Boundary_Family'],'divergent'],'#58d7e7',2.4],['tectonic-transform',['==',['get','Boundary_Family'],'transform'],'#d58cff',2.2],['tectonic-other',['==',['get','Boundary_Family'],'other'],'#8aa4aa',1.5]];
  for(const [id,filter,color,width] of specs)if(!map.getLayer(id))map.addLayer({id,type:'line',source:'plate-steps',filter,paint:{'line-color':color,'line-width':['interpolate',['linear'],['zoom'],0,width*.55,5,width,9,width*1.35],'line-opacity':.9}});
  if(!map.getSource('tectonic-selection'))map.addSource('tectonic-selection',{type:'geojson',data:empty});
  if(!map.getLayer('tectonic-selection-casing'))map.addLayer({id:'tectonic-selection-casing',type:'line',source:'tectonic-selection',paint:{'line-color':'#031a22','line-width':['interpolate',['linear'],['zoom'],0,6,5,9,9,13],'line-opacity':.9}});
  if(!map.getLayer('tectonic-selection'))map.addLayer({id:'tectonic-selection',type:'line',source:'tectonic-selection',paint:{'line-color':'#f4fbff','line-width':['interpolate',['linear'],['zoom'],0,3,5,5,9,7],'line-opacity':1}});
  if(!map.getSource('line-selection'))map.addSource('line-selection',{type:'geojson',data:empty});
  if(!map.getLayer('line-selection-casing'))map.addLayer({id:'line-selection-casing',type:'line',source:'line-selection',paint:{'line-color':'#031a22','line-width':['interpolate',['linear'],['zoom'],0,6,6,9,10,13],'line-opacity':.9}});
  if(!map.getLayer('line-selection'))map.addLayer({id:'line-selection',type:'line',source:'line-selection',paint:{'line-color':'#f4fbff','line-width':['interpolate',['linear'],['zoom'],0,3,6,5,10,7],'line-opacity':1}});
  if(map.getLayer('plates'))map.setPaintProperty('plates','line-opacity',.10);if(map.getLayer('plates-casing'))map.setPaintProperty('plates-casing','line-opacity',.08);
}
const addLayersBeforeTectonics=addLayers;addLayers=function(){addLayersBeforeTectonics();ensureTectonicLayers();restoreTectonicSelection();restoreLineSelection()};
let selectedTectonicStep=null,selectedLineFeature=null;
function restoreTectonicSelection(){ensureTectonicLayers();map.getSource('tectonic-selection')?.setData(selectedTectonicStep||empty)}
function restoreLineSelection(){ensureTectonicLayers();map.getSource('line-selection')?.setData(selectedLineFeature||empty)}
function selectTectonicStep(f){selectedTectonicStep={type:'Feature',properties:{...(f.properties||{})},geometry:f.geometry};selectedLineFeature=null;map.getSource('selection')?.setData(empty);restoreTectonicSelection();restoreLineSelection()}
/* The generic P1 selection renderer is a circle layer. Feeding a LineString to it produced a cyan circle at every vertex. Lines get a proper line highlight instead. */
const selectFeatureBeforeLineFix=selectFeature;selectFeature=function(layer,f){const isLine=f?.geometry?.type==='LineString'||f?.geometry?.type==='MultiLineString';if(!isLine){selectedLineFeature=null;restoreLineSelection();return selectFeatureBeforeLineFix(layer,f)}selectedTectonicStep=null;restoreTectonicSelection();selectedMapFeature={layer,feature:{type:'Feature',properties:{...(f.properties||{})},geometry:f.geometry}};selectedLineFeature=selectedMapFeature.feature;map.getSource('selection')?.setData(empty);restoreLineSelection();detail(layer,f)};
async function loadTectonicContext(){const [steps,polygons]=await Promise.all([localSnapshot('plate-steps.json','plateSteps'),localSnapshot('plate-polygons.json','platePolygons')]);plateStepData=steps?.features?steps:empty;platePolygonData=polygons?.features?polygons:empty;ensureTectonicLayers();map.getSource('plate-steps')?.setData(plateStepData);map.getSource('plate-polygons')?.setData(platePolygonData);restoreTectonicSelection();restoreLineSelection()}
function pointInRing(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j],hit=((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1]||1e-12)+a[0]);if(hit)inside=!inside}return inside}function pointInPolygon(p,g){if(!g)return false;const poly=rings=>rings?.length&&pointInRing(p,rings[0])&&!rings.slice(1).some(r=>pointInRing(p,r));return g.type==='Polygon'?poly(g.coordinates):g.type==='MultiPolygon'?g.coordinates.some(poly):false}function containingPlate(coords){return platePolygonData.features.find(f=>pointInPolygon(coords,f.geometry))||null}
function boundaryContext(coords){const hit=plateStepData.features.length?nearestLine(coords,plateStepData):null;if(!hit)return null;const p=hit.feature.properties||{},code=value(p.Boundary_Code,p.STEPCLASS),meta=STEP_META[code]||{family:value(p.Boundary_Family,'other'),label:value(p.Boundary_Label,'Plate boundary')};return {...hit,code,family:meta.family,label:value(p.Boundary_Label,meta.label),pair:value(p.Plate_Pair,p.PLATEBOUND)}}function plateName(f){if(!f)return null;const p=f.properties||{};return value(p.Plate_Name,p.PlateName,p.Name,p.NAME,p.Plate_Code,p.Code)}
const relationshipsBeforeTectonics=relationships;relationships=function(coords){const boundary=boundaryContext(coords),plate=containingPlate(coords),fault=faultData.features.length?nearestLine(coords,faultData):null,qs=nearbyQuakes(coords,quakeData,250),strong=qs[0];if(!boundary&&!plate)return relationshipsBeforeTectonics(coords);const tectonic=`<div class="inspector-section tectonic-context"><div class="inspector-heading">Tectonic context</div><div class="context-primary">${plate?`<div><b>${esc(plateName(plate))}</b><span>PB2002 plate</span></div>`:''}${boundary?`<div><b>${esc(boundary.label)}</b><span>${boundary.pair?esc(boundary.pair)+' · ':''}${Math.round(boundary.distance)} km away</span></div>`:''}</div></div>`;const nearby=`<div class="inspector-section"><div class="inspector-heading">Nearby</div><div class="relationship-grid"><div><b>${boundary?Math.round(boundary.distance)+' km':'—'}</b><span>${boundary?esc(boundary.label.toLowerCase()):'nearest typed boundary'}</span></div><div><b>${qs.length}</b><span>earthquakes / 250 km (${historicalMode?'search':'current'})</span></div><div><b>${strong?`M ${Number(strong.properties.mag).toFixed(1)}`:'—'}</b><span>${strong?`${Math.round(strong._distance)} km away`:'strongest nearby'}</span></div><div><b>${fault?Math.round(fault.distance)+' km':viewState.layers.faults?'—':'off'}</b><span>nearest active fault</span></div></div></div>`;return tectonic+nearby};
function showTectonicDetail(f){selectTectonicStep(f);const p=f.properties||{},code=value(p.Boundary_Code,p.STEPCLASS),meta=STEP_META[code]||{label:'Plate boundary',family:'other'},body=document.querySelector('#details-body');body.innerHTML=`<div class="eyebrow">Plate tectonics · ${esc(code||'PB2002')}</div><h2>${esc(value(p.Boundary_Label,meta.label))}</h2><div class="inspector-section"><div class="inspector-heading">Boundary</div><div class="meta">${fact('Class',meta.family)}${fact('Plate pair',value(p.Plate_Pair,p.PLATEBOUND))}${fact('Step length',p.STEPLENGTH!=null?`${Number(p.STEPLENGTH).toFixed(1)} km`:null)}${fact('Relative velocity',p.VELOCITYLE!=null?`${Number(p.VELOCITYLE).toFixed(1)} mm/yr`:null)}</div></div><div class="inspector-section"><div class="inspector-heading">Source</div><p class="source">PB2002 · Peter Bird (2003)</p></div>`;document.querySelector('#details').hidden=false}
function nearbyRenderedFeature(point,layers,radius=9){const existing=layers.filter(id=>map.getLayer(id));if(!existing.length)return null;const box=[[point.x-radius,point.y-radius],[point.x+radius,point.y+radius]],hits=map.queryRenderedFeatures(box,{layers:existing});if(!hits.length)return null;const click=[point.x,point.y],distance=f=>{const coords=f.geometry?.coordinates;if(!coords)return Infinity;const lines=f.geometry.type==='LineString'?[coords]:f.geometry.type==='MultiLineString'?coords:[];let best=Infinity;for(const line of lines)for(let i=1;i<line.length;i++){const a=map.project(line[i-1]),b=map.project(line[i]),dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((click[0]-a.x)*dx+(click[1]-a.y)*dy)/(dx*dx+dy*dy||1)));best=Math.min(best,Math.hypot(click[0]-(a.x+t*dx),click[1]-(a.y+t*dy)))}return best};return hits.sort((a,b)=>distance(a)-distance(b))[0]}
const hoverPopup=new maplibregl.Popup({closeButton:false,closeOnClick:false,offset:12});let hoverKey='';
function tooltipFor(f,kind){const p=f.properties||{};if(kind==='tectonic'){const code=value(p.Boundary_Code,p.STEPCLASS),meta=STEP_META[code]||{label:'Plate boundary'},pair=value(p.Plate_Pair,p.PLATEBOUND),v=Number(p.VELOCITYLE);return `<strong>${esc(value(p.Boundary_Label,meta.label))}</strong>${pair?`<br>${esc(pair)}`:''}${Number.isFinite(v)?`<br>${v.toFixed(1)} mm/yr relative velocity`:''}<br><small>Click for details</small>`}if(kind==='fault')return `<strong>${esc(value(p.name,p.Name,p.fault_name,'Mapped active fault'))}</strong>${value(p.slip_type,p.slip_type_text,p.sense)?`<br>${esc(value(p.slip_type,p.slip_type_text,p.sense))}`:''}<br><small>GEM active fault · click for details</small>`;if(kind==='earthquakes')return `<strong>M ${esc(value(p.mag,'?'))}</strong><br>${esc(value(p.place,'Earthquake'))}<br><small>${historicalMode?'USGS historical catalog':'USGS live feed'} · click for details</small>`;if(kind==='activity')return `<strong>Weekly volcanic report</strong><br>${esc(value(p.Volcano_Name,p.Report_Name,'Volcano'))}<br><small>Smithsonian / USGS · click for report</small>`;return `<strong>${esc(value(p.Volcano_Name,p.VolcanoName,'Known volcano'))}</strong>${value(p.Country)?`<br>${esc(p.Country)}`:''}<br><small>Smithsonian GVP catalog · click for details</small>`}
function pointHoverFeature(point){const layers=POINT_HOVER_LAYERS.filter(id=>map.getLayer(id)&&map.getLayoutProperty(id,'visibility')!=='none'),hits=layers.length?map.queryRenderedFeatures(point,{layers}):[];if(!hits.length)return null;const priority={activity:0,volcanoes:1,earthquakes:2};hits.sort((a,b)=>(priority[a.layer.id]??9)-(priority[b.layer.id]??9));return {feature:hits[0],kind:hits[0].layer.id}}
function updateHover(e){const pointHit=pointHoverFeature(e.point),t=nearbyRenderedFeature(e.point,TECTONIC_LAYERS,8),f=viewState.layers.faults&&map.getLayer('faults')?nearbyRenderedFeature(e.point,['faults'],9):null,hit=pointHit?.feature||t||f,kind=pointHit?.kind||(t?'tectonic':f?'fault':null);if(!hit){hoverKey='';hoverPopup.remove();map.getCanvas().style.cursor='';return}map.getCanvas().style.cursor='pointer';const p=hit.properties||{},key=`${kind}:${value(p.id,p.code,p.Volcano_Number,p.Volcano_Name,p.Boundary_Code,p.STEPCLASS,p.name,p.Name,p.place,'feature')}`;if(key!==hoverKey){hoverKey=key;hoverPopup.setHTML(tooltipFor(hit,kind))}hoverPopup.setLngLat(e.lngLat).addTo(map)}
map.on('click',e=>{const direct=map.queryRenderedFeatures(e.point,{layers:TECTONIC_LAYERS.filter(id=>map.getLayer(id))});if(direct.length)return;const tectonic=nearbyRenderedFeature(e.point,TECTONIC_LAYERS,10);if(tectonic){showTectonicDetail(tectonic);return}if(viewState.layers.faults&&map.getLayer('faults')){const fault=nearbyRenderedFeature(e.point,['faults'],11);if(fault)selectFeature('faults',fault)}});map.on('mousemove',updateHover);map.on('mouseout',()=>{hoverKey='';hoverPopup.remove()});for(const id of TECTONIC_LAYERS)map.on('click',id,e=>{const f=e.features?.[0];if(f)showTectonicDetail(f)});
document.querySelector('#details-close')?.addEventListener('click',()=>{selectedTectonicStep=null;selectedLineFeature=null;map.getSource('tectonic-selection')?.setData(empty);map.getSource('line-selection')?.setData(empty)});loadTectonicContext();
