/* P1 runtime: resilient map lifecycle, source-aware inspector, relationships + history. */
let selectedMapFeature=null,selectionPulseFrame=0,historicalMode=false,historicalData=empty;
function ensureSelectionLayer(){if(!map.getSource('selection'))map.addSource('selection',{type:'geojson',data:empty});if(!map.getLayer('selection-casing'))map.addLayer({id:'selection-casing',type:'circle',source:'selection',paint:{'circle-radius':14,'circle-color':'rgba(0,0,0,0)','circle-stroke-color':'rgba(3,26,34,.82)','circle-stroke-width':6,'circle-stroke-opacity':.82}});if(!map.getLayer('selection'))map.addLayer({id:'selection',type:'circle',source:'selection',paint:{'circle-radius':14,'circle-color':'rgba(99,215,230,.10)','circle-stroke-color':'#63d7e6','circle-stroke-width':3,'circle-stroke-opacity':1}})}
function restoreSelection(){ensureSelectionLayer();map.getSource('selection')?.setData(selectedMapFeature?.feature||empty)}
function animateSelection(ts=0){if(map.getLayer('selection')&&selectedMapFeature){const p=(Math.sin(ts/360)+1)/2,r=12+p*8;map.setPaintProperty('selection','circle-radius',r);map.setPaintProperty('selection','circle-stroke-width',2.5+p*1.5);map.setPaintProperty('selection','circle-stroke-opacity',1-p*.35);if(map.getLayer('selection-casing'))map.setPaintProperty('selection-casing','circle-radius',r)}selectionPulseFrame=requestAnimationFrame(animateSelection)}selectionPulseFrame=requestAnimationFrame(animateSelection);
const originalAddLayers=addLayers;addLayers=function(){originalAddLayers();restoreSelection()};
selectFeature=function(layer,f){selectedMapFeature={layer,feature:{type:'Feature',properties:{...(f.properties||{})},geometry:f.geometry}};restoreSelection();detail(layer,f)};
document.querySelector('#details-close').addEventListener('click',()=>{selectedMapFeature=null;map.getSource('selection')?.setData(empty)});
let styleChangeToken=0;changeBasemap=function(name){if(!BASEMAPS[name]||name===viewState.basemap)return;const token=++styleChangeToken;saveCamera();viewState.basemap=name;saveState();loading(true);const camera={...viewState.camera},projection=viewState.projection;let settled=false,finish=()=>{if(settled||token!==styleChangeToken)return;settled=true;loading(false)};map.once('style.load',()=>{if(token!==styleChangeToken)return;try{addLayers();setProjection(projection,false);map.jumpTo({...camera});applyVisibility();restoreSelection();requestAnimationFrame(()=>requestAnimationFrame(finish))}catch(e){console.error('Basemap rehydrate failed',e);finish()}});try{map.setStyle(BASEMAPS[name],{diff:false})}catch(e){console.error('Basemap change failed',e);finish()}setTimeout(finish,8000)};

let dataManifest=null;async function localSnapshot(path,label){try{const r=await fetch(`./data/${path}`,{cache:'no-cache'});if(!r.ok)throw Error(r.status);const d=await r.json();failures.delete(label);setStatus();return d}catch(e){failures.add(label);setStatus();console.warn(`local ${label} snapshot unavailable`,e);return null}}
async function loadManifest(){try{const r=await fetch('./data/manifest.json',{cache:'no-cache'});if(!r.ok)throw Error(r.status);dataManifest=await r.json()}catch(e){console.warn('data manifest unavailable',e)}}
function snapshotAge(){const raw=dataManifest?.generatedAt;if(!raw)return'';const ms=Date.now()-Date.parse(raw);if(!Number.isFinite(ms))return'';const h=Math.max(0,Math.floor(ms/36e5));return h<24?`${h}h old`:`${Math.floor(h/24)}d old`}
const baseSetStatus=setStatus;setStatus=function(){baseSetStatus();const el=document.querySelector('#status'),age=snapshotAge();if(el&&age)el.textContent+=` · snapshot ${age}`};
loadVolcanoes=async()=>{const d=await localSnapshot('volcanoes.json','volcanoes');volcanoData=d?.features?d:empty;map.getSource('volcanoes')?.setData(volcanoData);document.querySelector('#volcano-count').textContent=volcanoData.features.length};loadPlates=async()=>{const d=await localSnapshot('plates.json','plates');plateData=d?.features?d:empty;map.getSource('plates')?.setData(plateData)};loadActivity=async()=>{const d=await localSnapshot('volcanic-reports.json','activity');activityData=d?.features?d:empty;map.getSource('activity')?.setData(activityData);document.querySelector('#activity-count').textContent=activityData.features.length};loadFaults=async()=>{if(faultData.features.length)return;document.querySelector('#fault-count').textContent='…';const d=await localSnapshot('faults.json','faults');faultData=d?.features?d:empty;map.getSource('faults')?.setData(faultData);document.querySelector('#fault-count').textContent=faultData.features.length};
function value(...xs){return xs.find(x=>x!==undefined&&x!==null&&String(x).trim()&&String(x).trim().toLowerCase()!=='unknown')??null}function fmtDate(raw){if(!raw)return null;const d=new Date(raw);return Number.isNaN(d.valueOf())?String(raw):d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}function fact(l,v){return v==null||String(v).trim()===''?'':`<div class="fact"><b>${esc(l)}</b>${esc(v)}</div>`}
function volcanoCatalogMatch(p){const id=String(value(p.Volcano_Number,p.VolcanoNumber,p.volcano_number)||''),name=value(p.Volcano_Name,p.VolcanoName,p.volcano_name,p.Report_Name);return volcanoData.features.find(v=>{const q=v.properties||{};return(id&&String(value(q.Volcano_Number,q.VolcanoNumber,q.volcano_number)||'')===id)||(name&&norm(value(q.Volcano_Name,q.VolcanoName,q.volcano_name))===norm(name))})}function reportsForVolcano(p){const id=String(value(p.Volcano_Number,p.VolcanoNumber,p.volcano_number)||''),name=value(p.Volcano_Name,p.VolcanoName,p.volcano_name);return activityData.features.filter(v=>{const q=v.properties||{};return(id&&String(value(q.Volcano_Number,q.VolcanoNumber,q.volcano_number)||'')===id)||(name&&norm(value(q.Volcano_Name,q.VolcanoName,q.volcano_name))===norm(name))})}function reportForVolcano(p){return reportsForVolcano(p)[0]}
const rad=x=>x*Math.PI/180;function haversine(a,b){const dlat=rad(b[1]-a[1]),dlon=rad(b[0]-a[0]),x=Math.sin(dlat/2)**2+Math.cos(rad(a[1]))*Math.cos(rad(b[1]))*Math.sin(dlon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function segments(g){const out=[];if(!g)return out;const walk=c=>{if(typeof c?.[0]==='number'){return}if(typeof c?.[0]?.[0]==='number'){for(let i=1;i<c.length;i++)out.push([c[i-1],c[i]])}else c?.forEach(walk)};walk(g.coordinates);return out}function pointSegmentKm(p,a,b){const lat=rad(p[1]),kx=111.32*Math.cos(lat),ky=110.57,px=p[0]*kx,py=p[1]*ky,ax=a[0]*kx,ay=a[1]*ky,bx=b[0]*kx,by=b[1]*ky,dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy))}function nearestLine(p,data){let best=null;for(const f of data.features||[])for(const [a,b] of segments(f.geometry)){const d=pointSegmentKm(p,a,b);if(!best||d<best.distance)best={distance:d,feature:f}}return best}
function nearbyQuakes(coords,data=quakeData,radius=250){return(data.features||[]).map(f=>({...f,_distance:haversine(coords,f.geometry.coordinates)})).filter(f=>f._distance<=radius).sort((a,b)=>b.properties.mag-a.properties.mag)}
function relationships(coords){const boundary=nearestLine(coords,plateData),fault=faultData.features.length?nearestLine(coords,faultData):null,qs=nearbyQuakes(coords,quakeData,250),strong=qs[0];return `<div class="inspector-section"><div class="inspector-heading">Nearby</div><div class="relationship-grid"><div><b>${boundary?Math.round(boundary.distance)+' km':'—'}</b><span>nearest plate boundary</span></div><div><b>${qs.length}</b><span>earthquakes / 250 km (${historicalMode?'search':'current'})</span></div><div><b>${strong?`M ${Number(strong.properties.mag).toFixed(1)}`:'—'}</b><span>${strong?`${Math.round(strong._distance)} km away`:'strongest nearby'}</span></div><div><b>${fault?Math.round(fault.distance)+' km':viewState.layers.faults?'—':'off'}</b><span>nearest active fault</span></div></div></div>`}
function historySection(p){const reports=reportsForVolcano(p).slice().sort((a,b)=>Date.parse(value(b.properties?.Report_Published,b.properties?.Report_Date)||0)-Date.parse(value(a.properties?.Report_Published,a.properties?.Report_Date)||0));const eruption=value(p.Last_Known_Eruption,p.LastKnownEruption,p.last_known_eruption);if(!reports.length&&!eruption)return'';return `<div class="inspector-section"><div class="inspector-heading">History</div><div class="timeline">${reports.slice(0,6).map(r=>`<div class="timeline-item"><time>${esc(fmtDate(value(r.properties?.Report_Published,r.properties?.Report_Date))||'Report')}</time><span>GVP weekly activity report</span></div>`).join('')}${eruption?`<div class="timeline-item"><time>${esc(eruption)}</time><span>Last known eruption (GVP catalog)</span></div>`:''}</div></div>`}
function volcanoDetail(f){const incoming=f.properties||{},catalog=volcanoCatalogMatch(incoming),p={...(catalog?.properties||{}),...incoming},report=reportForVolcano(p),rp=report?.properties||{},coords=(catalog?.geometry||f.geometry)?.coordinates||[],name=value(p.Volcano_Name,p.VolcanoName,p.volcano_name,rp.Volcano_Name,'Volcano'),number=value(p.Volcano_Number,p.VolcanoNumber,p.volcano_number),country=value(p.Country,p.country),type=value(p.Primary_Volcano_Type,p.PrimaryVolcanoType,p.primary_volcano_type,p.Volcano_Type,p.volcano_type),elevation=value(p.Elevation_m,p.Elevation,p.elevation_m),eruption=value(p.Last_Known_Eruption,p.LastKnownEruption,p.last_known_eruption),tectonic=value(p.Tectonic_Setting,p.TectonicSetting,p.tectonic_setting),reportTitle=value(rp.Report_Name,rp.Report_Title),reportDate=fmtDate(value(rp.Report_Published,rp.Report_Date,rp.report_published)),summary=value(rp.Report_Summary,rp.Summary),reportUrl=value(rp.Report_URL,SOURCES.activity.url),hasReport=!!report,loc=[country,Number.isFinite(+coords[1])&&Number.isFinite(+coords[0])?`${(+coords[1]).toFixed(3)}, ${(+coords[0]).toFixed(3)}`:null].filter(Boolean).join(' · ');return `<div class="eyebrow">Volcano${number?` · GVP ${esc(number)}`:''}</div><h2>🌋 ${esc(name)}</h2>${hasReport?'<span class="live-badge">Weekly activity report</span>':''}<div class="inspector-section"><div class="inspector-heading">Overview</div><div class="meta">${fact('Location',loc)}${fact('Volcano type',type)}${fact('Elevation',elevation!=null?`${elevation} m`:null)}${fact('Last known eruption',eruption)}${fact('Tectonic setting',tectonic)}</div></div>${hasReport?`<div class="inspector-section activity-section"><div class="inspector-heading">Latest weekly report</div>${reportDate?`<div class="report-date">Published ${esc(reportDate)}</div>`:''}${reportTitle&&norm(reportTitle)!==norm(name)?`<div class="report-title">${esc(reportTitle)}</div>`:''}${summary?`<p class="report-summary">${esc(summary)}</p>`:''}<a href="${esc(reportUrl)}" target="_blank" rel="noreferrer">Open GVP weekly report ↗</a><p class="semantic-note">A Weekly Volcanic Activity Report is noteworthy activity, not an official alert level or a complete list of erupting volcanoes.</p></div>`:''}${historySection(p)}${coords.length>=2?relationships(coords):''}<div class="inspector-section"><div class="inspector-heading">Sources</div>${sourceLine(SOURCES.volcanoes)}${hasReport?sourceLine(SOURCES.activity):''}${snapshotAge()?`<p class="source">Open Earth snapshot: ${esc(snapshotAge())}</p>`:''}</div>`}
const baseDetail=detail;detail=function(layer,f){const body=document.querySelector('#details-body'),panel=document.querySelector('#details');if((layer==='volcanoes'||layer==='activity')&&body){body.innerHTML=volcanoDetail(f);panel.hidden=false;return}baseDetail(layer,f);if(body&&snapshotAge())body.insertAdjacentHTML('beforeend',`<p class="source">Open Earth snapshot: ${esc(snapshotAge())}</p>`)};
function localVolcanoSearch(query){const q=norm(query);if(!q)return[];return volcanoData.features.filter(f=>{const n=norm(value(f.properties?.Volcano_Name,f.properties?.VolcanoName,f.properties?.volcano_name));return n===q||n.startsWith(q)||n.includes(q)}).sort((a,b)=>{const an=norm(value(a.properties?.Volcano_Name,a.properties?.VolcanoName)),bn=norm(value(b.properties?.Volcano_Name,b.properties?.VolcanoName));return Number(bn===q)-Number(an===q)||Number(bn.startsWith(q))-Number(an.startsWith(q))}).slice(0,6)}
const searchInput=document.querySelector('#search'),searchResults=document.querySelector('#search-results');searchInput?.addEventListener('input',()=>{const hits=localVolcanoSearch(searchInput.value);if(!hits.length)return;searchResults.innerHTML=hits.map((f,i)=>`<button type="button" data-local-volcano="${i}">🌋 ${esc(value(f.properties?.Volcano_Name,f.properties?.VolcanoName))}${f.properties?.Country?` · ${esc(f.properties.Country)}`:''}</button>`).join('');searchResults.hidden=false;searchResults.querySelectorAll('[data-local-volcano]').forEach(btn=>btn.addEventListener('click',()=>{const f=hits[+btn.dataset.localVolcano],c=f.geometry.coordinates,r=reportForVolcano(f);searchInput.value=value(f.properties?.Volcano_Name,f.properties?.VolcanoName);searchResults.hidden=true;map.flyTo({center:c,zoom:8});selectFeature(r?'activity':'volcanoes',r||f)}))},true);

/* USGS FDSN historical catalog. Radius search uses selected feature; otherwise current map bounds. */
const histStart=document.querySelector('#history-start'),histEnd=document.querySelector('#history-end'),histMag=document.querySelector('#history-mag'),histRadius=document.querySelector('#history-radius'),histSelected=document.querySelector('#history-selected'),histStatus=document.querySelector('#history-status');if(histEnd&&!histEnd.value){const end=new Date(),start=new Date(end);start.setUTCFullYear(end.getUTCFullYear()-1);histEnd.value=end.toISOString().slice(0,10);histStart.value=start.toISOString().slice(0,10)}
async function historicalSearch(){const params=new URLSearchParams({format:'geojson',starttime:histStart.value,endtime:histEnd.value,minmagnitude:histMag.value||'0',orderby:'time',limit:'20000'}),sel=selectedMapFeature?.feature?.geometry?.coordinates;if(histSelected.checked&&sel?.length>=2){params.set('latitude',sel[1]);params.set('longitude',sel[0]);params.set('maxradiuskm',histRadius.value||'250')}else{const b=map.getBounds();params.set('minlatitude',b.getSouth());params.set('maxlatitude',b.getNorth());params.set('minlongitude',b.getWest());params.set('maxlongitude',b.getEast())}histStatus.textContent='Searching USGS catalog…';try{const r=await fetch(`https://earthquake.usgs.gov/fdsnws/event/1/query?${params}`);if(!r.ok)throw Error(`${r.status} ${await r.text()}`);historicalData=await r.json();historicalMode=true;quakeData=historicalData;map.getSource('earthquakes')?.setData(quakeData);document.querySelector('#quake-count').textContent=quakeData.features.length;histStatus.textContent=`${quakeData.features.length.toLocaleString()} historical earthquakes · ${histStart.value} → ${histEnd.value}`;document.querySelectorAll('#range button').forEach(b=>b.classList.remove('active'));if(selectedMapFeature)detail(selectedMapFeature.layer,selectedMapFeature.feature)}catch(e){console.error('Historical earthquake search failed',e);histStatus.textContent=`USGS search failed: ${e.message}`}}
async function backToLive(){historicalMode=false;histStatus.textContent='Live earthquake feed restored.';await loadQuakes(viewState.earthquakeRange);document.querySelectorAll('#range button').forEach(b=>b.classList.toggle('active',b.dataset.range===viewState.earthquakeRange));if(selectedMapFeature)detail(selectedMapFeature.layer,selectedMapFeature.feature)}
document.querySelector('#history-run')?.addEventListener('click',historicalSearch);document.querySelector('#history-live')?.addEventListener('click',backToLive);document.querySelector('#range')?.addEventListener('click',()=>{historicalMode=false});
loadManifest().then(setStatus);
